version: '3'

services:
  postgres:
    image: postgres:14
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=swapi
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=swapi
    restart: always

  api:
    build:
      context: .
      args:
        - NODE_ENV=development
        - PORT=3000
    ports:
      - 3000
    volumes:
      - .:/home/node/app
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://swapi:password@postgres:5432/swapi
    restart: always
    command: npm run start:dev
    depends_on:
      - postgres

volumes:
  postgres_data: